// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Camp defines model for Camp.
type Camp struct {
	Capacity  int                `json:"capacity"`
	CreatedAt time.Time          `json:"created_at"`
	EndDate   openapi_types.Date `json:"end_date"`
	Id        openapi_types.UUID `json:"id"`
	Location  string             `json:"location"`
	Name      string             `json:"name"`
	Sport     string             `json:"sport"`
	StartDate openapi_types.Date `json:"start_date"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// CampInput defines model for CampInput.
type CampInput struct {
	Capacity  int                `json:"capacity"`
	EndDate   openapi_types.Date `json:"end_date"`
	Location  string             `json:"location"`
	Name      string             `json:"name"`
	Sport     string             `json:"sport"`
	StartDate openapi_types.Date `json:"start_date"`
}

// CampList defines model for CampList.
type CampList struct {
	Items  []Camp `json:"items"`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ListCampsParams defines parameters for ListCamps.
type ListCampsParams struct {
	Sport  *string `form:"sport,omitempty" json:"sport,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCampJSONRequestBody defines body for CreateCamp for application/json ContentType.
type CreateCampJSONRequestBody = CampInput
