// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: camps.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamp = `-- name: CreateCamp :one
INSERT INTO camps (name, sport, location, capacity, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, sport, location, capacity, start_date, end_date, created_at, updated_at
`

type CreateCampParams struct {
	Name      string      `json:"name"`
	Sport     string      `json:"sport"`
	Location  string      `json:"location"`
	Capacity  int32       `json:"capacity"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateCamp(ctx context.Context, arg CreateCampParams) (Camp, error) {
	row := q.db.QueryRow(ctx, createCamp,
		arg.Name,
		arg.Sport,
		arg.Location,
		arg.Capacity,
		arg.StartDate,
		arg.EndDate,
	)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Capacity,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCamp = `-- name: DeleteCamp :exec
DELETE FROM camps WHERE id = $1
`

func (q *Queries) DeleteCamp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCamp, id)
	return err
}

const getCamp = `-- name: GetCamp :one
SELECT id, name, sport, location, capacity, start_date, end_date, created_at, updated_at FROM camps WHERE id = $1
`

func (q *Queries) GetCamp(ctx context.Context, id pgtype.UUID) (Camp, error) {
	row := q.db.QueryRow(ctx, getCamp, id)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Capacity,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCamps = `-- name: ListCamps :many
SELECT id, name, sport, location, capacity, start_date, end_date, created_at, updated_at FROM camps
WHERE ($1::text IS NULL OR sport = $1)
ORDER BY start_date ASC
LIMIT $3 OFFSET $2
`

type ListCampsParams struct {
	Sport  *string `json:"sport"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListCamps(ctx context.Context, arg ListCampsParams) ([]Camp, error) {
	rows, err := q.db.Query(ctx, listCamps, arg.Sport, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Camp
	for rows.Next() {
		var i Camp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sport,
			&i.Location,
			&i.Capacity,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamp = `-- name: UpdateCamp :one
UPDATE camps
SET name = $2,
    sport = $3,
    location = $4,
    capacity = $5,
    start_date = $6,
    end_date = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, sport, location, capacity, start_date, end_date, created_at, updated_at
`

type UpdateCampParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Sport     string      `json:"sport"`
	Location  string      `json:"location"`
	Capacity  int32       `json:"capacity"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateCamp(ctx context.Context, arg UpdateCampParams) (Camp, error) {
	row := q.db.QueryRow(ctx, updateCamp,
		arg.ID,
		arg.Name,
		arg.Sport,
		arg.Location,
		arg.Capacity,
		arg.StartDate,
		arg.EndDate,
	)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Capacity,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
