// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCamp(ctx context.Context, arg CreateCampParams) (Camp, error)
	DeleteCamp(ctx context.Context, id pgtype.UUID) error
	GetCamp(ctx context.Context, id pgtype.UUID) (Camp, error)
	ListCamps(ctx context.Context, arg ListCampsParams) ([]Camp, error)
	UpdateCamp(ctx context.Context, arg UpdateCampParams) (Camp, error)
}

var _ Querier = (*Queries)(nil)
